---
- name: Testear mapeo de unidad R desde NAS Synology
  hosts: windows
  gather_facts: no

  tasks:
    - name: Mapear unidad R:
      win_shell: >
        net use R: "\\{{ nas_ip }}\{{ nas_share }}" /user:{{ nas_user }} {{ nas_password }} /persistent:no
      register: net_use_output
      changed_when: false

    - name: Mostrar salida de net use
      debug:
        var: net_use_output.stdout_lines

    - name: Listar archivos en R:\
      win_shell: dir R:\
      register: listado_R

    - name: Mostrar contenido de R:\
      debug:
        var: listado_R.stdout_lines
