- name: Save CSV on PC-003 desktop
  hosts: PC-003
  gather_facts: no

  vars:
    csv_path: "C:\\Users\\{{ ansible_user }}\\Desktop\\hardware_report.csv"

  tasks:
    - name: Collect hw_info from all hosts
      set_fact:
        all_hw_info: "{{ groups['all'] | map('extract', hostvars, 'hw_info') | list }}"

    - name: Write hardware info to CSV using PowerShell
      win_shell: |
        $csvPath = '{{ csv_path }}'
        $allData = @(
          {% for item in all_hw_info %}
          [pscustomobject]@{
            Hostname = '{{ item.hostname }}'
            FQDN = '{{ item.ansible_fqdn }}'
            CPUCores = '{{ item.cpu_cores }}'
            MemoryMB = '{{ item.memory_mb }}'
            DiskSizeGB = '{{ item.disk_size_gb }}'
          }
          {% if not loop.last %}, {% endif %}
          {% endfor %}
        )
        $allData | Export-Csv -Path $csvPath -NoTypeInformation -Encoding UTF8
      args:
        executable: powershell.exe
