---
- name: Extraer info hardware completa y guardar en un JSON por host
  hosts: windows
  gather_facts: no
  tasks:
    - name: Obtener info CPU
      win_shell: |
        Get-CimInstance Win32_Processor | Select-Object Name,NumberOfCores,MaxClockSpeed | ConvertTo-Json -Depth 5
      register: cpu_info

    - name: Obtener info RAM
      win_shell: |
        Get-CimInstance Win32_PhysicalMemory | Select-Object Capacity,Speed,Manufacturer | ConvertTo-Json -Depth 5
      register: ram_info

    - name: Obtener info discos
      win_shell: |
        Get-CimInstance Win32_DiskDrive | Select-Object Model,Size,InterfaceType | ConvertTo-Json -Depth 5
      register: disk_info

    - name: Obtener info placa base
      win_shell: |
        Get-CimInstance Win32_BaseBoard | Select-Object Manufacturer,Product,SerialNumber | ConvertTo-Json -Depth 5
      register: baseboard_info

    - name: Crear estructura JSON con toda la info
      set_fact:
        hardware_info: |
          {
            "CPU": {{ cpu_info.stdout }},
            "RAM": {{ ram_info.stdout }},
            "Discos": {{ disk_info.stdout }},
            "PlacaBase": {{ baseboard_info.stdout }}
          }

    - name: Crear carpeta local para guardar info hardware
      local_action:
        module: file
        path: "./hardware_info"
        state: directory

    - name: Guardar JSON completo en master
      copy:
        content: "{{ hardware_info }}"
        dest: "./hardware_info/{{ inventory_hostname }}_hardware.json"
      delegate_to: localhost
