---
- name: Warn Windows users of impending upgrade
  hosts: windows
  gather_facts: no
  tasks:
    - name: Warn logged in users of impending upgrade (from Semaphore variable)
      community.windows.win_toast:
        expire: 60
        title: System Upgrade Notification
        msg: "{{ lookup('env', 'POPUP_MESSAGE') | template }}"
      vars:
        deployment_start_time: "6:00 PM"
      async: 60
      poll: 0
