---
- name: Alert Windows user with a message
  hosts: windows
  gather_facts: no
  tasks:
    - name: Send popup message using PowerShell
      win_shell: |
        Add-Type -AssemblyName PresentationFramework
        [System.Windows.MessageBox]::Show('This is Ansible speaking!', 'Ansible Alert')
