---
- name: Alert Windows user with msg.exe
  hosts: windows
  gather_facts: no
  tasks:
    - name: Send console message to logged in user
      win_shell: |
        $username = (query user | Select-String "Active").ToString().Split(' ')[0]
        msg $username "This is Ansible speaking!"
