---
- name: Alert Windows user with a message asynchronously
  hosts: windows
  gather_facts: no
  tasks:
    - name: Launch popup message in background
      win_shell: |
        Start-Process powershell -ArgumentList "-NoProfile -WindowStyle Hidden -Command `"Add-Type -AssemblyName PresentationFramework; [System.Windows.MessageBox]::Show('This is Ansible speaking!', 'Ansible Alert')`""
