---
- name: Alert Windows user with a message
  hosts: windows
  gather_facts: no
  tasks:
    - name: Send popup message to Windows user
      win_message:
        msg: "This is Ansible speaking!"
        title: "Ansible Alert"
